# Data Preparation For Fine Grained Attributes

In [1]:
import pandas as pd 
import numpy as np 

paths_df = pd.read_csv("../datasets/attribute_set/train_fine_grained.txt", names=["paths"], sep=" ", header=None)

In [3]:
paths_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14000 entries, 0 to 13999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   paths   14000 non-null  object
dtypes: object(1)
memory usage: 109.5+ KB

In [13]:
columns = pd.read_csv("../datasets/attribute_set/fine_grained_column_names.txt", header=None, delimiter=" ").to_numpy().squeeze()

In [5]:
attr_df = pd.read_csv("../datasets/attribute_set/train_attr_fine_grained.txt", header=None, delimiter=" ").iloc[:, :-1]
attr_df.columns = columns
attr_df.head()

,floral,graphic,striped,embroidered,pleated,solid,lattice,long_sleeve,short_sleeve,sleeveless,...,no_neckline,denim,chiffon,cotton,leather,faux,knit,tight,loose,conventional
0,0,0,0,1,0,0,0,0,0,1,...,1,0,1,0,0,0,0,0,0,1
1,0,0,0,0,0,1,0,0,0,1,...,1,0,0,1,0,0,0,1,0,0
2,0,1,0,0,0,0,0,0,0,1,...,1,0,0,1,0,0,0,0,0,1
3,0,0,0,0,0,1,0,0,0,1,...,1,1,0,0,0,0,0,1,0,0
4,0,0,0,0,0,1,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1

In [6]:
attr_df.shape, paths_df.shape

((14000, 26), (14000, 1))

In [7]:
base = "../datasets/big_ds/img-001/" 
base

'../datasets/big_ds/img-001/'

In [8]:
paths_df = paths_df.apply(lambda x: base + x) 
paths_df.head()

                                               paths
0  ../datasets/big_ds/img-001/img/Sweet_Crochet_B...
1  ../datasets/big_ds/img-001/img/Classic_Pencil_...
2  ../datasets/big_ds/img-001/img/Strapless_Diamo...
3  ../datasets/big_ds/img-001/img/Mid-Rise_-_Acid...
4  ../datasets/big_ds/img-001/img/Zippered_Single...

In [9]:
data = pd.concat([paths_df, attr_df], axis=1)
data.head()

,paths,floral,graphic,striped,embroidered,pleated,solid,lattice,long_sleeve,short_sleeve,...,no_neckline,denim,chiffon,cotton,leather,faux,knit,tight,loose,conventional
0,../datasets/big_ds/img-001/img/Sweet_Crochet_B...,0,0,0,1,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,1
1,../datasets/big_ds/img-001/img/Classic_Pencil_...,0,0,0,0,0,1,0,0,0,...,1,0,0,1,0,0,0,1,0,0
2,../datasets/big_ds/img-001/img/Strapless_Diamo...,0,1,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,1
3,../datasets/big_ds/img-001/img/Mid-Rise_-_Acid...,0,0,0,0,0,1,0,0,0,...,1,1,0,0,0,0,0,1,0,0
4,../datasets/big_ds/img-001/img/Zippered_Single...,0,0,0,0,0,1,0,1,0,...,0,0,0,1,0,0,0,0,0,1

In [10]:
val_attr_df = pd.read_csv("../datasets/attribute_set/val_attr_fine_grained.txt", header=None, delimiter=" ").iloc[:, :-1]
val_attr_df.columns = columns
val_attr_df.head()

,floral,graphic,striped,embroidered,pleated,solid,lattice,long_sleeve,short_sleeve,sleeveless,...,no_neckline,denim,chiffon,cotton,leather,faux,knit,tight,loose,conventional
0,0,1,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1
1,0,0,0,0,0,1,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
2,0,0,0,0,0,1,0,0,0,1,...,1,1,0,0,0,0,0,0,0,1
3,0,0,0,0,0,1,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1
4,0,0,0,0,0,1,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1

In [15]:
val_paths_df = pd.read_csv("../datasets/attribute_set/val_fine_grained.txt", names=["paths"], sep=" ", header=None)
val_paths_df = val_paths_df.apply(lambda x: base + x) 
val_paths_df.head()

                                               paths
0  ../datasets/big_ds/img-001/img/Butterfly_Print...
1  ../datasets/big_ds/img-001/img/Varsity-Striped...
2  ../datasets/big_ds/img-001/img/Distressed_Deni...
3  ../datasets/big_ds/img-001/img/Collarless_Wove...
4  ../datasets/big_ds/img-001/img/Pin_Dot_Suit_Ja...

In [18]:
val_data = pd.concat([val_paths_df, val_attr_df], axis=1)
val_data.head()

,paths,floral,graphic,striped,embroidered,pleated,solid,lattice,long_sleeve,short_sleeve,...,no_neckline,denim,chiffon,cotton,leather,faux,knit,tight,loose,conventional
0,../datasets/big_ds/img-001/img/Butterfly_Print...,0,1,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,1
1,../datasets/big_ds/img-001/img/Varsity-Striped...,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,0
2,../datasets/big_ds/img-001/img/Distressed_Deni...,0,0,0,0,0,1,0,0,0,...,1,1,0,0,0,0,0,0,0,1
3,../datasets/big_ds/img-001/img/Collarless_Wove...,0,0,0,0,0,1,0,1,0,...,0,0,0,1,0,0,0,0,0,1
4,../datasets/big_ds/img-001/img/Pin_Dot_Suit_Ja...,0,0,0,0,0,1,0,1,0,...,0,0,0,1,0,0,0,0,0,1

In [19]:
val_data.shape, data.shape

((2000, 27), (14000, 27))

In [20]:
TRAIN_SIZE = 14000 

data = pd.concat([data, val_data], axis=0)

In [21]:
data.head()

,paths,floral,graphic,striped,embroidered,pleated,solid,lattice,long_sleeve,short_sleeve,...,no_neckline,denim,chiffon,cotton,leather,faux,knit,tight,loose,conventional
0,../datasets/big_ds/img-001/img/Sweet_Crochet_B...,0,0,0,1,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,1
1,../datasets/big_ds/img-001/img/Classic_Pencil_...,0,0,0,0,0,1,0,0,0,...,1,0,0,1,0,0,0,1,0,0
2,../datasets/big_ds/img-001/img/Strapless_Diamo...,0,1,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,1
3,../datasets/big_ds/img-001/img/Mid-Rise_-_Acid...,0,0,0,0,0,1,0,0,0,...,1,1,0,0,0,0,0,1,0,0
4,../datasets/big_ds/img-001/img/Zippered_Single...,0,0,0,0,0,1,0,1,0,...,0,0,0,1,0,0,0,0,0,1

In [22]:
data.tail()

,paths,floral,graphic,striped,embroidered,pleated,solid,lattice,long_sleeve,short_sleeve,...,no_neckline,denim,chiffon,cotton,leather,faux,knit,tight,loose,conventional
1995,../datasets/big_ds/img-001/img/Embroidered_Pea...,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
1996,../datasets/big_ds/img-001/img/Tasmanian_Devil...,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,1,0,0,1
1997,../datasets/big_ds/img-001/img/Lace-Sleeved_Ra...,0,0,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,1
1998,../datasets/big_ds/img-001/img/Floral_Mosaic_P...,1,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,1
1999,../datasets/big_ds/img-001/img/Sparkling_Ruche...,0,0,0,1,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,1

In [24]:
# data.to_csv("../datasets/attribute_set/train_val_data_fine_grained_all.csv")

# Test Dataset

In [2]:
paths_test_df = pd.read_csv("../datasets/attribute_set/test.txt", names=["paths"], sep=" ", header=None)

In [4]:
paths_test_df.shape

(4000, 1)

In [8]:
paths_test_df.shape

(4000, 1)

In [16]:
attr_test_df = pd.read_csv("../datasets/attribute_set/test_attr.txt", header=None, delimiter=" ").iloc[:, :-1]
attr_test_df.columns = columns
attr_test_df.head()

,floral,graphic,striped,embroidered,pleated,solid,lattice,long_sleeve,short_sleeve,sleeveless,...,no_neckline,denim,chiffon,cotton,leather,faux,knit,tight,loose,conventional
0,1,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,1,0,0
1,0,0,0,0,1,0,0,1,0,0,...,1,0,1,0,0,0,0,0,0,1
2,0,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
3,1,0,0,0,0,0,0,0,0,1,...,1,0,0,1,0,0,0,0,0,1
4,0,0,0,0,0,1,0,0,0,1,...,0,0,1,0,0,0,0,0,0,1

In [18]:
data_test = pd.concat([paths_test_df, attr_test_df], axis=1)

In [19]:
data_test.head()

,paths,floral,graphic,striped,embroidered,pleated,solid,lattice,long_sleeve,short_sleeve,...,no_neckline,denim,chiffon,cotton,leather,faux,knit,tight,loose,conventional
0,img/Floral_Print_Shirt_Dress/img_00000065.jpg,1,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
1,img/Butterfly_Sleeve_Sheath_Dress/img_00000034...,0,0,0,0,1,0,0,1,0,...,1,0,1,0,0,0,0,0,0,1
2,img/Marled_Crochet-Back_Sweater/img_00000038.jpg,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,1,0,0,1
3,img/Sunburst_Print_Swim_Trunks/img_00000008.jpg,1,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,1
4,img/Collared_Surplice_Blouse/img_00000022.jpg,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [21]:
# data_test.to_csv("../datasets/attribute_set/test_data_fine_grained.csv")